const fs = require('fs');
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: {
    main: ['./src/index.js']
  },
  output: {
    path: __dirname + `/public`,
    filename: '[name].js',
    publicPath: '/'
  },
  module: {
    rules: [
      {
        test: /\.js/,
        exclude: /node_modules/,
        loader: 'babel-loader',
      }
    ]
  },
  resolve: {
    extensions: ['.js'],
    modules: ['node_modules', path.join(__dirname, "src")],
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'index.html',
      inject: true // Inject all files that are generated by webpack, e.g. bundle.js
    }),
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
      }
    })
  ],
};